### ISSUE TITLE
Configuration file issue

### ISSUE THREAD

**Issue by shideneyu** [technekes/grape-apiary#4]
Following the `README`, I created an `apiary.rb` in an Initializer. Then I cannot boot my server due to this error:

    ➜  webscrap_master_service git:(new_api) ✗ rails console
    WARNING: The rest_client gem is deprecated and will be removed from RubyGems. Please use rest-client gem instead.
    /home/shideneyu/projects/Textmaster/webscrap_master_service/config/initializers/apiary.rb:13:in `block in <top (required)>': undefined method `include_root=' for GrapeApiary::Config:Class (NoMethodError)
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-apiary-0.0.4/lib/grape-apiary.rb:14:in `config'
      from /home/shideneyu/projects/Textmaster/webscrap_master_service/config/initializers/apiary.rb:1:in `<top (required)>'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/engine.rb:652:in `block in load_config_initializer'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/engine.rb:651:in `load_config_initializer'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/engine.rb:615:in `each'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/engine.rb:615:in `block in <class:Engine>'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `each'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `tsort_each_child'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:411:in `call'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
      from /home/shideneyu/projects/Textmaster/webscrap_master_service/config/environment.rb:5:in `<top (required)>'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:67:in `console'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
      from /home/shideneyu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
      from bin/rails:4:in `require'
      from bin/rails:4:in `<main>'

I can resolve this issue by commenting this:

    config.include_root       = true

But I highly doubt that this is a good solution.

**Comment by johnallen3d** [comment]
Hello @shideneyu, sorry for the delayed response. I've just tried to duplicate this issue but am not having any success. Here is what I'm using:

```ruby
# app.rb
require 'grape-apiary'

GrapeApiary.config do |config|
  config.host               = 'http://awesome-api.apiary.io'
  config.name               = 'Awesome API'
  config.description        = 'The awesome description'
  config.example_id_type    = :uuid
  config.resource_exclusion = [:admin, :swagger_doc]
  config.include_root       = true
end

puts "include root? #{GrapeApiary.config.include_root}"
```

When I run it there is no error:

```shell
> ruby app.rb
include root? true
```

Is this still an issue for you? If so can you provide a reproducible example?

**Comment by johnallen3d** [comment]
Closing due to lack of response and inability to reproduce.
